C:\Users\xavi_\AppData\Local\Temp\ipykernel_21800\3022674731.py:24: UserWarning: Using a target size (torch.Size([64, 3, 32, 32])) that is different to the input size (torch.Size([64, 1, 32, 32])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  loss = criterion(out, image_y)
Epoch: 0/3000
| Training loss:  0.05867599695920944