2023-06-01 17:07:58,337 INFO    MainThread:21800 [wandb_setup.py:_flush():76] Configure stats pid to 21800
2023-06-01 17:07:58,338 INFO    MainThread:21800 [wandb_setup.py:_flush():76] Loading settings from C:\Users\xavi_\.config\wandb\settings
2023-06-01 17:07:58,338 INFO    MainThread:21800 [wandb_setup.py:_flush():76] Loading settings from d:\Math of ML Master - HSE\Skoltech\ICNN\wandb\settings
2023-06-01 17:07:58,338 INFO    MainThread:21800 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'api_key': '***REDACTED***'}
2023-06-01 17:07:58,338 INFO    MainThread:21800 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-06-01 17:07:58,338 INFO    MainThread:21800 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-06-01 17:07:58,338 INFO    MainThread:21800 [wandb_init.py:_log_setup():506] Logging user logs to d:\Math of ML Master - HSE\Skoltech\ICNN\wandb\run-20230601_170758-tooy4xzl\logs\debug.log
2023-06-01 17:07:58,339 INFO    MainThread:21800 [wandb_init.py:_log_setup():507] Logging internal logs to d:\Math of ML Master - HSE\Skoltech\ICNN\wandb\run-20230601_170758-tooy4xzl\logs\debug-internal.log
2023-06-01 17:07:58,339 INFO    MainThread:21800 [wandb_init.py:_jupyter_setup():452] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002672A1C7F70>
2023-06-01 17:07:58,339 INFO    MainThread:21800 [wandb_init.py:init():546] calling init triggers
2023-06-01 17:07:58,339 INFO    MainThread:21800 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {'dataset': 'MNIST-FMNIST', 'machine': 'Colab', 'model': 'unet', 'loss_function': 'l1_loss', 'image_size': 32, 'learning_rate': 0.001, 'batch_size_loop': 64, 'batch_size_paired': 128, 'epochs': 3000}
2023-06-01 17:07:58,339 INFO    MainThread:21800 [wandb_init.py:init():568] re-initializing run, found existing run on stack: 86qftlhx
2023-06-01 17:07:58,341 INFO    MainThread:21800 [wandb_run.py:_finish():1854] finishing run icnn-23/FMNIST-dense_icnn-False-l1_loss-t/86qftlhx
2023-06-01 17:07:58,341 INFO    MainThread:21800 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-06-01 17:07:58,342 INFO    MainThread:21800 [wandb_run.py:_restore():2066] restore
2023-06-01 17:07:58,342 INFO    MainThread:21800 [wandb_run.py:_restore():2072] restore done
2023-06-01 17:08:03,765 INFO    MainThread:21800 [wandb_run.py:_footer_history_summary_info():3422] rendering history
2023-06-01 17:08:03,767 INFO    MainThread:21800 [wandb_run.py:_footer_history_summary_info():3454] rendering summary
2023-06-01 17:08:03,801 INFO    MainThread:21800 [wandb_run.py:_footer_sync_info():3380] logging synced files
2023-06-01 17:08:03,835 INFO    MainThread:21800 [wandb_init.py:init():602] starting backend
2023-06-01 17:08:03,836 INFO    MainThread:21800 [wandb_init.py:init():606] setting up manager
2023-06-01 17:08:03,867 INFO    MainThread:21800 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-06-01 17:08:03,887 INFO    MainThread:21800 [wandb_init.py:init():613] backend started and connected
2023-06-01 17:08:03,901 INFO    MainThread:21800 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2023-06-01 17:08:03,902 INFO    MainThread:21800 [wandb_run.py:_label_probe_notebook():1214] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-06-01 17:08:03,902 INFO    MainThread:21800 [wandb_init.py:init():701] updated telemetry
2023-06-01 17:08:04,000 INFO    MainThread:21800 [wandb_init.py:init():741] communicating run to backend with 60.0 second timeout
2023-06-01 17:08:05,507 INFO    MainThread:21800 [wandb_run.py:_on_init():2133] communicating current version
2023-06-01 17:08:05,720 INFO    MainThread:21800 [wandb_run.py:_on_init():2142] got version response upgrade_message: "wandb version 0.15.3 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-06-01 17:08:05,720 INFO    MainThread:21800 [wandb_init.py:init():789] starting run threads in backend
2023-06-01 17:08:05,994 INFO    MainThread:21800 [wandb_run.py:_console_start():2114] atexit reg
2023-06-01 17:08:05,995 INFO    MainThread:21800 [wandb_run.py:_redirect():1969] redirect: SettingsConsole.WRAP_RAW
2023-06-01 17:08:05,995 INFO    MainThread:21800 [wandb_run.py:_redirect():2034] Wrapping output streams.
2023-06-01 17:08:05,995 INFO    MainThread:21800 [wandb_run.py:_redirect():2059] Redirects installed.
2023-06-01 17:08:05,996 INFO    MainThread:21800 [wandb_init.py:init():831] run started, returning control to user process
2023-06-01 17:09:40,087 INFO    MainThread:21800 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-06-01 17:09:40,088 INFO    MainThread:21800 [wandb_init.py:_pause_backend():417] pausing backend
2023-06-01 17:09:50,997 INFO    MainThread:21800 [wandb_init.py:_resume_backend():422] resuming backend
2023-06-01 17:09:52,521 INFO    MainThread:21800 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-06-01 17:09:52,522 INFO    MainThread:21800 [wandb_init.py:_pause_backend():417] pausing backend
2023-06-01 17:12:30,218 INFO    MainThread:21800 [wandb_init.py:_resume_backend():422] resuming backend
2023-06-01 17:12:30,280 INFO    MainThread:21800 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-06-01 17:12:30,280 INFO    MainThread:21800 [wandb_init.py:_pause_backend():417] pausing backend
2023-06-01 17:12:32,549 INFO    MainThread:21800 [wandb_init.py:_resume_backend():422] resuming backend
2023-06-01 17:12:32,554 INFO    MainThread:21800 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-06-01 17:12:32,555 INFO    MainThread:21800 [wandb_init.py:_pause_backend():417] pausing backend
2023-06-01 17:12:33,954 INFO    MainThread:21800 [wandb_init.py:_resume_backend():422] resuming backend
2023-06-01 17:12:33,965 INFO    MainThread:21800 [wandb_setup.py:_flush():76] Configure stats pid to 21800
2023-06-01 17:12:33,965 INFO    MainThread:21800 [wandb_setup.py:_flush():76] Loading settings from C:\Users\xavi_\.config\wandb\settings
2023-06-01 17:12:33,966 INFO    MainThread:21800 [wandb_setup.py:_flush():76] Loading settings from d:\Math of ML Master - HSE\Skoltech\ICNN\wandb\settings
2023-06-01 17:12:33,966 INFO    MainThread:21800 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'api_key': '***REDACTED***'}
2023-06-01 17:12:33,966 INFO    MainThread:21800 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-06-01 17:12:33,966 INFO    MainThread:21800 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-06-01 17:12:33,967 INFO    MainThread:21800 [wandb_init.py:_log_setup():506] Logging user logs to d:\Math of ML Master - HSE\Skoltech\ICNN\wandb\run-20230601_171233-6zbkez61\logs\debug.log
2023-06-01 17:12:33,967 INFO    MainThread:21800 [wandb_init.py:_log_setup():507] Logging internal logs to d:\Math of ML Master - HSE\Skoltech\ICNN\wandb\run-20230601_171233-6zbkez61\logs\debug-internal.log
2023-06-01 17:12:33,967 INFO    MainThread:21800 [wandb_init.py:init():546] calling init triggers
2023-06-01 17:12:33,967 INFO    MainThread:21800 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {'dataset': 'MNIST-FMNIST', 'machine': 'Colab', 'model': 'unet', 'loss_function': 'l1_loss', 'image_size': 32, 'learning_rate': 0.001, 'batch_size_loop': 64, 'batch_size_paired': 128, 'epochs': 3000}
2023-06-01 17:12:33,967 INFO    MainThread:21800 [wandb_init.py:init():568] re-initializing run, found existing run on stack: tooy4xzl
2023-06-01 17:12:33,969 INFO    MainThread:21800 [wandb_run.py:_finish():1854] finishing run icnn-23/FMNIST-unet-False-l1_loss-t/tooy4xzl
2023-06-01 17:12:33,970 ERROR   MainThread:21800 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2023-06-01 17:12:33,970 INFO    MainThread:21800 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-06-01 17:12:33,970 INFO    MainThread:21800 [wandb_init.py:_jupyter_teardown():434] cleaning up jupyter logic
2023-06-01 17:12:33,970 INFO    MainThread:21800 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2023-06-01 17:12:33,971 INFO    MainThread:21800 [wandb_run.py:_restore():2066] restore
2023-06-01 17:12:33,971 INFO    MainThread:21800 [wandb_run.py:_restore():2072] restore done
2023-06-01 17:12:40,118 INFO    MainThread:21800 [wandb_run.py:_footer_history_summary_info():3422] rendering history
2023-06-01 17:12:40,120 INFO    MainThread:21800 [wandb_run.py:_footer_history_summary_info():3454] rendering summary
2023-06-01 17:12:40,156 INFO    MainThread:21800 [wandb_run.py:_footer_sync_info():3380] logging synced files
